services:
  ollama:
    build:
      context: ./docker/ollama
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${OLLAMA_PORT}:11434"
    volumes:
      - ollama:/root/.ollama
      - ./models:/models:ro
    restart: unless-stopped
    gpus: all

volumes:
  ollama:
