services:
  ollama:
    build:
      context: ./docker/ollama
      dockerfile: Dockerfile
      args:
        - OLLAMA_PORT=${OLLAMA_PORT}
        - MODEL_NAME=${MODEL_NAME}
        - MODEL_BASE=${MODEL_BASE}
    restart: unless-stopped
    ports:
      - "${OLLAMA_PORT}:${OLLAMA_PORT}"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - anima_ll_data:/root/.ollama

volumes:
  anima_ll_data:
    name: anima_ll_data
